### ISSUE TITLE
Unable to open the website

### ISSUE THREAD

**Issue by earik87** [InsciteAnalytics/worldbank-climate-dashboard#1]
Hi Ali, 

I am unable to reach the [website](https://worldbank-climate-dashboard.herokuapp.com/main) at the moment. Refresh it several times but after a long time of loading it throws an application error. 

![image](https://user-images.githubusercontent.com/36437947/89410828-b72a0400-d724-11ea-8ae1-c91f923603f6.png)

The website is not maintained anymore?

**Comment by InsciteAnalytics** [comment]
Hi Enis, thanks for notifying and sorry for the delay; I was caught up in other projects. Sorry to hear about this; the reason is primarily free hosting on heroku. However, I just checked and it worked for me on first refresh. So once the title of the page changes to Panel application, that means its working; but the dashboard still takes a few seconds more to load. In terms of browsers, firefox is probably your best bet to load it successfully. Let me know how it turns out, all the best!

**Comment by earik87** [comment]
Hi Ali. I tried again in Chrome (I do not use firefox). Takes really long time until page title changes to Panel Application. There, another 10-20 seconds (maybe more), the dashboard is loaded finally. So it works again, thanks. 

But launch time is very long. Do not know why. 🙂

**Comment by InsciteAnalytics** [comment]
Well, a number of reasons:
1. The environment in the container is over 3 GB (primarily because of the polygon world map).
2. The app is being hosted on Heroku and is running on free dynos. Once the app is inactive for 30 min, the dynos shut off and have to be reactivated for the next load which requires additional time and often causes browser time outs.
3. I've tried chrome for loading it as well and it probably is the worst browser for this purpose which is a shame given it has 67 or so percent market share lol.
